language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
  - pip install unittest2
  - pip install -r pip-requirements
  - pip install .

# command to install dependencies
script: cd test; python test_fits2hdf.py
branches:
  only:
    - master